# Generated by Django 4.2.29 on 2026-04-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departamento",
            name="pais",
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_region", models.CharField(max_length=250)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.pais",
                    ),
                ),
            ],
            options={
                "db_table": "region",
            },
        ),
        migrations.AddField(
            model_name="departamento",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appontripadministracion.region",
            ),
            preserve_default=False,
        ),
    ]
