# Generated by Django 4.2.29 on 2026-04-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0002_remove_departamento_pais_region_departamento_region",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_destino",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "email_responsable_documentacion",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.municipio",
                    ),
                ),
            ],
            options={
                "db_table": "destinos_turisticos",
            },
        ),
        migrations.RemoveField(
            model_name="destinosturisticos",
            name="destino",
        ),
        migrations.DeleteModel(
            name="AsignarDestinosTuristicos",
        ),
        migrations.DeleteModel(
            name="DestinosTuristicos",
        ),
    ]
