# Generated by Django 4.2.29 on 2026-04-05 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0003_destinoturistico_remove_destinosturisticos_destino_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="destinoturistico",
            table="destinosturisticos",
        ),
    ]
