# Generated by Django 4.2.29 on 2026-04-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0004_alter_destinoturistico_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinoturistico",
            name="Detalle_ubicacion",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="Url_video_informativo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="Url_video_promocional",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Corregimiento",
        ),
    ]
