# Generated by Django 4.2.29 on 2026-04-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0005_destinoturistico_detalle_ubicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinoturistico",
            name="Clima",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="Recomendaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="Tipo_acceso",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="Vias_acceso",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="email_responsable_destino",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="actividadturistica",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre_actividad_turistica", models.CharField(max_length=250)),
                ("Descripcion", models.TextField()),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "Id_destino_turistico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
            ],
            options={
                "db_table": "actividadturistica",
            },
        ),
    ]
