# Generated by Django 4.2.29 on 2026-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0006_destinoturistico_clima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadturistica",
            name="Duracion",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Enfoque",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Equipamiento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Modalidad",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Nivel",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Observacion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Precio",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Recomendaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividadturistica",
            name="Zonas",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="actividadturistica",
            name="Descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
