# Generated by Django 4.2.29 on 2026-04-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0007_actividadturistica_duracion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Correo", models.EmailField(max_length=254)),
                ("Celular", models.CharField(max_length=50)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                ("Fecha_inicio", models.DateField()),
                ("Fecha_fin", models.DateField()),
                (
                    "Valor_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "paquetesturisticos",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Numero_personas", models.IntegerField(default=1)),
                (
                    "Valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "Descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("Total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("Forma_pago", models.CharField(max_length=100)),
                ("Vendedor", models.CharField(max_length=250)),
                ("Fecha_reserva", models.DateTimeField(auto_now_add=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "Id_liente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.cliente",
                    ),
                ),
                (
                    "Id_paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.paqueteturistico",
                    ),
                ),
            ],
            options={
                "db_table": "reservas",
            },
        ),
        migrations.CreateModel(
            name="PaqueteDestino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Id_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
                (
                    "Id_paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.paqueteturistico",
                    ),
                ),
            ],
            options={
                "db_table": "paquete_destino",
            },
        ),
        migrations.CreateModel(
            name="PaqueteActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Id_actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.actividadturistica",
                    ),
                ),
                (
                    "Id_paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.paqueteturistico",
                    ),
                ),
            ],
            options={
                "db_table": "paquete_actividad",
            },
        ),
    ]
