# Generated by Django 4.2.29 on 2026-04-29 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0008_cliente_paqueteturistico_reserva_paquetedestino_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reserva",
            old_name="Id_liente",
            new_name="Id_cliente",
        ),
    ]
