# Generated by Django 4.2.29 on 2026-04-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0009_rename_id_liente_reserva_id_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="Direccion",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="Id_municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appontripadministracion.municipio",
            ),
        ),
    ]
