# Generated by Django 4.2.29 on 2026-05-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0010_cliente_direccion_cliente_id_municipio"),
    ]

    operations = [
        migrations.CreateModel(
            name="fotografias",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Imagen", models.ImageField(upload_to="galeria/")),
                (
                    "Descripcion",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("Autor", models.CharField(blank=True, max_length=250, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "Actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="appontripadministracion.actividadturistica",
                    ),
                ),
                (
                    "Destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
            ],
            options={
                "db_table": "fotografias",
            },
        ),
    ]
