# Generated by Django 4.2.29 on 2026-05-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0011_fotografias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadturistica",
            name="Id_destino_turistico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="appontripadministracion.destinoturistico",
            ),
        ),
        migrations.CreateModel(
            name="EstablecimientoTuristico",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250, unique=True)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                ("Detalle_ubicacion", models.CharField(max_length=800)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "Id_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establecimientos",
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
            ],
            options={
                "db_table": "establecimientosturisticos",
            },
        ),
    ]
