# Generated by Django 4.2.29 on 2026-05-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0012_alter_actividadturistica_id_destino_turistico_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoAlojamiento",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "db_table": "tipoalojamiento",
            },
        ),
        migrations.CreateModel(
            name="Alojamiento",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250, unique=True)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                ("Detalle_ubicacion", models.CharField(max_length=800)),
                ("Checkin", models.TimeField(blank=True, null=True)),
                ("Checkout", models.TimeField(blank=True, null=True)),
                (
                    "Precio",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=15, null=True
                    ),
                ),
                (
                    "Id_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
                (
                    "Id_establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alojamientos",
                        to="appontripadministracion.establecimientoturistico",
                    ),
                ),
                (
                    "Id_tipoalojamiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.tipoalojamiento",
                    ),
                ),
            ],
            options={
                "db_table": "alojamiento",
            },
        ),
    ]
