# Generated by Django 4.2.29 on 2026-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0013_tipoalojamiento_alojamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="alojamiento",
            name="Numero_personas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alojamiento",
            name="Precio",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
