# Generated by Django 4.2.29 on 2026-05-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0014_alojamiento_numero_personas_alter_alojamiento_precio",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Turismo",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250, unique=True)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                ("Estado", models.BooleanField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "turismo",
            },
        ),
        migrations.CreateModel(
            name="destinotipoturismo",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "Id_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
                (
                    "Id_turismo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.turismo",
                    ),
                ),
            ],
            options={
                "db_table": "destinotipoturismo",
            },
        ),
    ]
