# Generated by Django 4.2.29 on 2026-05-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0015_turismo_destinotipoturismo"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="Id_pais",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appontripadministracion.pais",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="tiposturismo",
            field=models.ManyToManyField(
                related_name="destinos",
                through="appontripadministracion.destinotipoturismo",
                to="appontripadministracion.turismo",
            ),
        ),
        migrations.AlterField(
            model_name="destinotipoturismo",
            name="Id_destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinotipoturismo",
                to="appontripadministracion.destinoturistico",
            ),
        ),
    ]
