# Generated by Django 4.2.29 on 2026-05-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0016_departamento_id_pais_destinoturistico_tiposturismo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="equipotrabajo",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Formacion_academica", models.CharField(max_length=250)),
                ("Cargo", models.CharField(max_length=250)),
                ("Descripcion", models.TextField()),
            ],
            options={
                "db_table": "equipotrabajo",
            },
        ),
        migrations.CreateModel(
            name="eventos",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Descripcion", models.TextField()),
                ("Fecha_evento", models.TextField()),
                ("Fecha_inicio", models.DateTimeField()),
                ("Fecha_fin", models.DateTimeField()),
                ("Detalle_ubicacion", models.CharField(max_length=250)),
                ("Imagen_portada", models.ImageField(upload_to="eventos/")),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.municipio",
                    ),
                ),
            ],
            options={
                "db_table": "eventos",
            },
        ),
        migrations.CreateModel(
            name="nosotros",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre_sistema", models.CharField(max_length=250)),
                ("Slogan", models.CharField(max_length=250)),
                ("Descripcion", models.TextField()),
                ("Objetivo", models.TextField()),
                ("Mision", models.TextField()),
                ("Vision", models.TextField()),
                ("Historia", models.TextField()),
                ("Email_contacto", models.EmailField(max_length=254)),
                ("Telefono_contacto", models.CharField(max_length=13)),
                ("Facebook", models.URLField(blank=True, null=True)),
                ("Intagram", models.URLField(blank=True, null=True)),
                ("Estado", models.BooleanField()),
                ("Fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "nosotros",
            },
        ),
        migrations.CreateModel(
            name="tipoevento",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "tipoevento",
            },
        ),
        migrations.CreateModel(
            name="tipoproducto",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Descripcion", models.TextField()),
            ],
            options={
                "db_table": "tipoproducto",
            },
        ),
        migrations.CreateModel(
            name="productos",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                ("Envios_nacionales", models.BooleanField(blank=True, null=True)),
                ("Envios_internacionales", models.BooleanField(blank=True, null=True)),
                (
                    "Id_tipoproducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.tipoproducto",
                    ),
                ),
            ],
            options={
                "db_table": "productos",
            },
        ),
        migrations.CreateModel(
            name="eventotipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Id_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.eventos",
                    ),
                ),
                (
                    "Id_tipoevento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appontripadministracion.tipoevento",
                    ),
                ),
            ],
            options={
                "db_table": "eventotipo",
            },
        ),
    ]
