# Generated by Django 4.2.29 on 2026-05-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "appontripadministracion",
            "0017_equipotrabajo_eventos_nosotros_tipoevento_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="atractivoturistico",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=250)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                ("Historia", models.TextField(blank=True, null=True)),
                (
                    "Categoria",
                    models.CharField(
                        choices=[
                            ("iglesia", "Iglesia"),
                            ("museo", "Museo"),
                            ("parque", "Parque"),
                            ("mirador", "Mirador"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Id_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atractivos",
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
            ],
            options={
                "db_table": "atractivosturisticos",
            },
        ),
    ]
