# Generated by Django 4.2.29 on 2026-05-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0018_atractivoturistico"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografias",
            name="Portada",
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="atractivoturistico",
            name="Id_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atractivosturisticos",
                to="appontripadministracion.destinoturistico",
            ),
        ),
    ]
