# Generated by Django 4.2.29 on 2026-05-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0019_fotografias_portada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinosMasConsultados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_consulta", models.DateTimeField(auto_now_add=True)),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas",
                        to="appontripadministracion.destinoturistico",
                    ),
                ),
            ],
            options={
                "db_table": "destinosmasconsultados",
            },
        ),
    ]
