# Generated by Django 4.2.29 on 2026-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appontripadministracion", "0020_destinosmasconsultados"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinoturistico",
            name="latitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="destinoturistico",
            name="longitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
